#!/usr/bin/env bash
#scrot -q 100 '%Y-%m-%d_$wx$h.png' -e 'mv $f ~/Imágenes/screenshots/' -e 'feh -. %Y-%m-%d_$wx$h.png'
scrot -q 100 '%Y-%m-%d_$wx$h.png' -e 'mv $f ~/Imágenes/screenshots/ | notify-send Screenshot_taken ~/Imágenes/screenshots/$f'
